name: Deploy the application to Google Cloud Run
on:
  push:
    branches: [ master ]
jobs:
  setup-build-publish-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: GoogleCloudPlatform/github-actions@0.1.2
      with:
        service_account_key: ${{ secrets.GCLOUD_AUTH }}
