name: Deploy the application to Google Cloud Run
on:
  push:
    branches:
      - 'master'

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@master
      # Setup gcloud CLI
      - name: Setup gcloud environment
        uses: GoogleCloudPlatform/github-actions@0.1.2
        with:
          version: '270.0.0'
          service_account_key: ${{ secrets.GCLOUD_AUTH }}

        # Configure docker to use the gcloud command-line tool as a credential helper
      - name: Setup
      - run: |-
          # Set up docker to authenticate
          # via gcloud command-line tool.
          gcloud auth configure-docker

        # Build the Docker image
      - name: Build
        run: |-
          docker build . --tag eu.gcr.io/${{ secrets.GCLOUD_PROJECT }}/${{ secrets.GCLOUD_APP_NAME }}:${CAT_VERSION}


        #Push the Docker image to Google Container Registry
      - name: Publish
        run: |-
          docker push eu.gcr.io/${{ secrets.GCLOUD_PROJECT }}/${{ secrets.GCLOUD_NAME }}:${CAT_VERSION}

        # Deploy the Docker image to the GKE cluster
      - name: Deploy
        run: |-
          gcloud components install beta && gcloud beta run deploy ${{ secrets.GCLOUD_NAME }} --quiet --image eu.gcr.io/${{ secrets.GCLOUD_PROJECT }}/${{ secrets.GCLOUD_NAME }} --project ${{ secrets.GCLOUD_PROJECT }} --region europe-west1 --platform managed
